### ISSUE TITLE
problems with some widths and heights on bitmap

### ISSUE THREAD

**Issue by miguelknb** [zholos/js_bitmap#2]
Hey there,
I'm using this module to generate a bitmap out of an coordinates array to produce drawings based on the pixels storaged. My issue is that, when trying to bitmap with some width and heights, I'm getting an incorrect base64 string.

I also noticed that you used some octal escapes that are no longer supported in Js, and changed it to hexadecimal equivalents, that may be causing some problems but I'm not sure.

var bmp = new Bitmap(width, height)

        for(var i = 0; i < answerLength; i++) {
            bmp.pixel[Math.floor(points[i][0])][Math.floor(points[i][1])] = [1,0,0,1]
        }

        var url = bmp.dataURL()

Width and Height of my files normaly goes from 512x240 to 640x420

**Comment by zholos** [comment]
Thanks! Should be fixed now. Your bitmap size has more than 64 kB of data which needed to be split across several deflate blocks.

Note that for real world applications you should consider using [canvas.toDataUrl](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL) instead of this toy library. The data URLs will be much shorter then due to PNG compression.

**Comment by miguelknb** [comment]
Thanks a lot!
I used your library because was desperately in need of some image creation without using any canvas related method.
Again, thanks a lot!
